version: "2.4"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'    
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      # These are the settings to access your db
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: ${DB_PORT}
      DB_MYSQL_USER: "${DB_PWR}"
      DB_MYSQL_PASSWORD: "${DB_PWR}"
      DB_MYSQL_NAME: "${DB_PWR}"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    dns:
      - 8.8.8.8
      - 9.9.9.9
    depends_on:
      - db
  db:
    image: jc21/mariadb-aria:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${PWR}'
      MYSQL_DATABASE: '${PWR}'
      MYSQL_USER: '${PWR}'
      MYSQL_PASSWORD: '${PWR}'
    volumes:
      - ./data/mysql:/var/lib/mysql
  jenkins:
    image: 'jenkins/jenkins'
    ports:
      - '82:8080'
      - '5000:5000'
    volumes:
      - jenkins-data:/var/jenkins_home
volumes:
  jenkins-data:
networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.${IP_SUB_MERGED}.0.0/16
          gateway: 172.${IP_SUB_MERGED}.0.1
        - subnet: fd00:96cd:${IP_SUB_MERGED}::/96
          gateway: fd00:96cd:${IP_SUB_MERGED}::1
